/**
 * AI Race Analyst.
 *
 * Every answer ships with the citations that grounded it, and each one is
 * expandable, so "the AI said so" is never the end of the trail. When the
 * retrieval layer finds nothing, the answer says so rather than improvising.
 */

import { useEffect, useRef, useState } from 'react'
import { api } from '../lib/api'
import { useApi } from '../hooks/useApi'
import { Badge, Card, Loading, SectionTitle } from '../components/ui'
import { FeedbackWidget } from '../components/FeedbackWidget'
import { MAX_QUESTION_LENGTH, validateQuestion } from '../lib/validation'
import type { ChatResponse } from '../lib/types'

interface Turn {
  id: string
  role: 'user' | 'assistant'
  content: string
  response?: ChatResponse
}

export default function Analyst() {
  const [turns, setTurns] = useState<Turn[]>([])
  const [input, setInput] = useState('')
  const [sessionId, setSessionId] = useState<string | undefined>()
  const [pending, setPending] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const endRef = useRef<HTMLDivElement>(null)

  const suggestions = useApi(() => api.chatSuggestions(), [])
  const meta = useApi(() => api.meta(), [])

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' })
  }, [turns, pending])

  const send = async (question: string) => {
    if (pending) return
    const trimmed = question.trim()

    const validationError = validateQuestion(trimmed)
    if (validationError) {
      setError(validationError)
      return
    }

    setInput('')
    setError(null)
    setPending(true)
    setTurns((current) => [
      ...current,
      { id: `u-${Date.now()}`, role: 'user', content: trimmed },
    ])

    try {
      const response = await api.ask(trimmed, sessionId)
      setSessionId(response.session_id)
      setTurns((current) => [
        ...current,
        {
          id: `a-${response.message_id ?? Date.now()}`,
          role: 'assistant',
          content: response.answer,
          response,
        },
      ])
    } catch (err) {
      setError(err instanceof Error ? err.message : 'The analyst could not answer')
    } finally {
      setPending(false)
    }
  }

  return (
    <div className="space-y-4">
      <SectionTitle
        hint={
          meta.data
            ? `Answers are restricted to data held in this application (${meta.data.first_season}–${meta.data.last_season}). Generated by the ${meta.data.ai_generator === 'bedrock' ? 'Amazon Bedrock' : 'built-in template'} writer.`
            : undefined
        }
      >
        AI Race Analyst
      </SectionTitle>

      <Card className="flex h-[min(72vh,760px)] flex-col">
        <div className="flex-1 space-y-4 overflow-y-auto p-4 sm:p-5">
          {turns.length === 0 ? (
            <Welcome
              questions={suggestions.data?.questions ?? []}
              onPick={(question) => void send(question)}
            />
          ) : null}

          {turns.map((turn) =>
            turn.role === 'user' ? (
              <UserBubble key={turn.id} text={turn.content} />
            ) : (
              <AssistantBubble key={turn.id} turn={turn} />
            ),
          )}

          {pending ? <Loading label="Retrieving the data…" /> : null}
          {error ? (
            <p id="question-error" role="alert" className="text-sm text-status-bad">
              {error}
            </p>
          ) : null}
          <div ref={endRef} />
        </div>

        <form
          className="flex gap-2 border-t border-line p-3 sm:p-4"
          onSubmit={(event) => {
            event.preventDefault()
            void send(input)
          }}
        >
          <div className="flex-1">
            <input
              className={`input ${error ? '!border-status-bad' : ''}`}
              value={input}
              maxLength={MAX_QUESTION_LENGTH}
              onChange={(event) => {
                setInput(event.target.value)
                if (error) setError(null)
              }}
              placeholder="Ask about a driver, a team, a circuit or the next race…"
              aria-label="Your question"
              aria-invalid={error ? true : undefined}
              aria-describedby={error ? 'question-error' : undefined}
              disabled={pending}
            />
            {input.length > MAX_QUESTION_LENGTH - 100 ? (
              <p className="mt-1 text-right text-xs text-ink-muted">
                {MAX_QUESTION_LENGTH - input.length} characters left
              </p>
            ) : null}
          </div>
          <button
            type="submit"
            className="btn-primary self-start"
            disabled={pending || !input.trim()}
          >
            Ask
          </button>
        </form>
      </Card>
    </div>
  )
}

function Welcome({
  questions,
  onPick,
}: {
  questions: string[]
  onPick: (question: string) => void
}) {
  return (
    <div className="py-6 text-center">
      <p className="text-sm font-medium text-ink-primary">
        Ask a question about the data in this app.
      </p>
      <p className="mx-auto mt-1.5 max-w-lg text-xs leading-relaxed text-ink-muted">
        The analyst retrieves matching rows from the database before answering, and shows you which
        ones it used. If the data is not there, it will tell you rather than guess.
      </p>
      <div className="mx-auto mt-4 flex max-w-2xl flex-wrap justify-center gap-2">
        {questions.map((question) => (
          <button
            key={question}
            type="button"
            onClick={() => onPick(question)}
            className="chip text-left transition-colors hover:border-line-strong hover:text-ink-primary"
          >
            {question}
          </button>
        ))}
      </div>
    </div>
  )
}

function UserBubble({ text }: { text: string }) {
  return (
    <div className="flex justify-end">
      <p className="max-w-[80%] rounded-xl rounded-br-sm bg-series-1 px-3.5 py-2 text-sm text-white">
        {text}
      </p>
    </div>
  )
}

function AssistantBubble({ turn }: { turn: Turn }) {
  const [showSources, setShowSources] = useState(false)
  const response = turn.response

  return (
    <div className="max-w-[92%] space-y-2">
      <div className="rounded-xl rounded-bl-sm border border-line bg-surface-2 px-3.5 py-3">
        <Markdownish text={turn.content} />
      </div>

      {response ? (
        <div className="flex flex-wrap items-center gap-2 pl-1">
          <Badge tone={response.grounded ? 'good' : 'warn'}>
            {response.grounded ? 'Grounded in data' : 'No matching data'}
          </Badge>
          <Badge>{response.intent.replace(/_/g, ' ')}</Badge>
          {response.generator ? (
            <Badge>{response.generator === 'bedrock' ? 'Bedrock' : 'Template writer'}</Badge>
          ) : null}
          {response.citations.length > 0 ? (
            <button
              type="button"
              className="link text-xs"
              onClick={() => setShowSources((value) => !value)}
              aria-expanded={showSources}
            >
              {showSources ? 'Hide' : 'Show'} {response.citations.length} source
              {response.citations.length === 1 ? '' : 's'}
            </button>
          ) : null}
        </div>
      ) : null}

      {showSources && response ? (
        <ul className="ml-1 space-y-1.5 rounded-lg border border-line bg-surface-1 p-3">
          {response.citations.map((citation, index) => (
            <li key={index} className="text-xs leading-relaxed">
              <span className="font-mono text-ink-muted">{citation.source}</span>
              <span className="text-ink-secondary"> — {citation.detail}</span>
            </li>
          ))}
          {response.notes.length > 0 ? (
            <li className="border-t border-line pt-1.5 text-xs italic text-ink-muted">
              {response.notes.join(' ')}
            </li>
          ) : null}
        </ul>
      ) : null}

      {response?.message_id ? (
        <FeedbackWidget
          className="pl-1"
          surface="chat"
          referenceId={String(response.message_id)}
          context={{ intent: response.intent, grounded: response.grounded }}
        />
      ) : null}
    </div>
  )
}

/**
 * Minimal Markdown rendering for the subset the answers actually use:
 * `**bold**`, `_italic_`, `- bullets` and paragraph breaks.
 * A full Markdown parser would be a dependency and an XSS surface for no gain.
 */
function Markdownish({ text }: { text: string }) {
  const blocks = text.split('\n')

  return (
    <div className="space-y-1.5 text-sm leading-relaxed text-ink-secondary">
      {blocks.map((line, index) => {
        const trimmed = line.trim()
        if (!trimmed) return null

        const bullet = trimmed.startsWith('- ')
        const indented = line.startsWith('    - ')
        const content = bullet || indented ? trimmed.replace(/^-\s*/, '') : trimmed

        return (
          <p
            key={index}
            className={
              indented
                ? 'ml-8 flex gap-2 text-xs text-ink-muted'
                : bullet
                  ? 'ml-3 flex gap-2'
                  : ''
            }
          >
            {bullet || indented ? <span aria-hidden="true">•</span> : null}
            <span>{inline(content)}</span>
          </p>
        )
      })}
    </div>
  )
}

function inline(text: string) {
  // Split on **bold** and _italic_ markers, keeping the delimiters.
  const parts = text.split(/(\*\*[^*]+\*\*|_[^_]+_)/g)
  return parts.map((part, index) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return (
        <strong key={index} className="font-semibold text-ink-primary">
          {part.slice(2, -2)}
        </strong>
      )
    }
    if (part.startsWith('_') && part.endsWith('_') && part.length > 2) {
      return (
        <em key={index} className="text-ink-muted">
          {part.slice(1, -1)}
        </em>
      )
    }
    return <span key={index}>{part}</span>
  })
}
