"""add driver portrait columns

Revision ID: 3ae2fad2c3ad
Revises: c886a66d5deb
Create Date: 2026-09-27 17:22:04.832148
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ae2fad2c3ad'
down_revision: Union[str, None] = 'c886a66d5deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('image_author', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image_license', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('image_license_url', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('image_license_url')
        batch_op.drop_column('image_license')
        batch_op.drop_column('image_author')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
