"""initial schema

Revision ID: c886a66d5deb
Revises: 
Create Date: 2026-09-27 16:55:18.283447
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c886a66d5deb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=True),
    sa.Column('circuit_type', sa.String(length=40), nullable=True),
    sa.Column('overtaking_difficulty', sa.String(length=20), nullable=True),
    sa.Column('tyre_degradation', sa.String(length=20), nullable=True),
    sa.Column('pit_loss_seconds', sa.Float(), nullable=True),
    sa.Column('drs_zones', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circuits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circuits_ref'), ['ref'], unique=True)

    op.create_table('constructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('constructors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constructors_ref'), ['ref'], unique=True)

    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('permanent_number', sa.Integer(), nullable=True),
    sa.Column('given_name', sa.String(length=80), nullable=False),
    sa.Column('family_name', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_ref'), ['ref'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('intent', sa.String(length=40), nullable=True),
    sa.Column('generator', sa.String(length=32), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)

    op.create_table('constructor_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', 'constructor_id', name='uq_cstanding')
    )
    with op.batch_alter_table('constructor_standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constructor_standings_constructor_id'), ['constructor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_constructor_standings_season'), ['season'], unique=False)

    op.create_table('driver_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', 'driver_id', name='uq_dstanding')
    )
    with op.batch_alter_table('driver_standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_standings_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_standings_season'), ['season'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.String(length=80), nullable=True),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(length=16), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=True),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('weather', sa.String(length=40), nullable=True),
    sa.Column('total_laps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', name='uq_race_season_round')
    )
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_index('ix_race_season_round', ['season', 'round'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_circuit_id'), ['circuit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_season'), ['season'], unique=False)

    op.create_table('saved_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_comparisons_user_id'), ['user_id'], unique=False)

    op.create_table('pit_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('stop', sa.Integer(), nullable=False),
    sa.Column('lap', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', 'stop', name='uq_pit_race_driver_stop')
    )
    with op.batch_alter_table('pit_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pit_stops_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pit_stops_race_id'), ['race_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=True),
    sa.Column('podium_probability', sa.Float(), nullable=False),
    sa.Column('points_probability', sa.Float(), nullable=False),
    sa.Column('win_probability', sa.Float(), nullable=True),
    sa.Column('expected_position', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('top_factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', 'model_version', name='uq_prediction_race_driver_ver')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_race_id'), ['race_id'], unique=False)

    op.create_table('qualifying_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('q1_ms', sa.Integer(), nullable=True),
    sa.Column('q2_ms', sa.Integer(), nullable=True),
    sa.Column('q3_ms', sa.Integer(), nullable=True),
    sa.Column('best_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_quali_race_driver')
    )
    with op.batch_alter_table('qualifying_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualifying_results_constructor_id'), ['constructor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qualifying_results_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qualifying_results_race_id'), ['race_id'], unique=False)

    op.create_table('race_lap_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('laps_recorded', sa.Integer(), nullable=False),
    sa.Column('mean_ms', sa.Integer(), nullable=True),
    sa.Column('median_ms', sa.Integer(), nullable=True),
    sa.Column('best_ms', sa.Integer(), nullable=True),
    sa.Column('std_ms', sa.Integer(), nullable=True),
    sa.Column('trimmed_mean_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_lapsum_race_driver')
    )
    with op.batch_alter_table('race_lap_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_lap_summaries_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_lap_summaries_race_id'), ['race_id'], unique=False)

    op.create_table('race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=8), nullable=True),
    sa.Column('grid', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_rank', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_result_race_driver')
    )
    with op.batch_alter_table('race_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_results_constructor_id'), ['constructor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_results_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_results_race_id'), ['race_id'], unique=False)
        batch_op.create_index('ix_result_driver_race', ['driver_id', 'race_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_results', schema=None) as batch_op:
        batch_op.drop_index('ix_result_driver_race')
        batch_op.drop_index(batch_op.f('ix_race_results_race_id'))
        batch_op.drop_index(batch_op.f('ix_race_results_driver_id'))
        batch_op.drop_index(batch_op.f('ix_race_results_constructor_id'))

    op.drop_table('race_results')
    with op.batch_alter_table('race_lap_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_lap_summaries_race_id'))
        batch_op.drop_index(batch_op.f('ix_race_lap_summaries_driver_id'))

    op.drop_table('race_lap_summaries')
    with op.batch_alter_table('qualifying_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualifying_results_race_id'))
        batch_op.drop_index(batch_op.f('ix_qualifying_results_driver_id'))
        batch_op.drop_index(batch_op.f('ix_qualifying_results_constructor_id'))

    op.drop_table('qualifying_results')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_race_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_driver_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('pit_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pit_stops_race_id'))
        batch_op.drop_index(batch_op.f('ix_pit_stops_driver_id'))

    op.drop_table('pit_stops')
    with op.batch_alter_table('saved_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_comparisons_user_id'))

    op.drop_table('saved_comparisons')
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_races_season'))
        batch_op.drop_index(batch_op.f('ix_races_date'))
        batch_op.drop_index(batch_op.f('ix_races_circuit_id'))
        batch_op.drop_index('ix_race_season_round')

    op.drop_table('races')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('driver_standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_standings_season'))
        batch_op.drop_index(batch_op.f('ix_driver_standings_driver_id'))

    op.drop_table('driver_standings')
    with op.batch_alter_table('constructor_standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constructor_standings_season'))
        batch_op.drop_index(batch_op.f('ix_constructor_standings_constructor_id'))

    op.drop_table('constructor_standings')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_ref'))

    op.drop_table('drivers')
    with op.batch_alter_table('constructors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constructors_ref'))

    op.drop_table('constructors')
    with op.batch_alter_table('circuits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circuits_ref'))

    op.drop_table('circuits')
    # ### end Alembic commands ###
